// Generated by file "Role.xlsx"

export interface RoleItem {
  Id: number,
  Type: number
}

export const RoleData = {
  "20001": {
    Id: 20001,
    Type: 1
  },
  "20002": {
    Id: 20002,
    Type: 1
  },
  "20003": {
    Id: 20003,
    Type: 1
  },
  "20004": {
    Id: 20004,
    Type: 1
  },
  "20005": {
    Id: 20005,
    Type: 1
  },
  "20006": {
    Id: 20006,
    Type: 2
  },
  "20007": {
    Id: 20007,
    Type: 2
  }
}
