// Generated by file "Building.xlsx"

export interface BuildingItem {
  Id: number,
  Type: number,
  Offsets: number[]
}

export const BuildingData = {
  "10001": {
    Id: 10001,
    Type: 6,
    Offsets: []
  },
  "10002": {
    Id: 10002,
    Type: 3,
    Offsets: []
  },
  "10003": {
    Id: 10003,
    Type: 2,
    Offsets: []
  },
  "10004": {
    Id: 10004,
    Type: 1,
    Offsets: []
  },
  "10005": {
    Id: 10005,
    Type: 2,
    Offsets: []
  },
  "10006": {
    Id: 10006,
    Type: 4,
    Offsets: []
  },
  "10007": {
    Id: 10007,
    Type: 5,
    Offsets: []
  },
  "10008": {
    Id: 10008,
    Type: 2,
    Offsets: []
  },
  "10009": {
    Id: 10009,
    Type: 2,
    Offsets: []
  },
  "10010": {
    Id: 10010,
    Type: 5,
    Offsets: []
  },
  "10011": {
    Id: 10011,
    Type: 4,
    Offsets: []
  },
  "10012": {
    Id: 10012,
    Type: 4,
    Offsets: []
  },
  "10013": {
    Id: 10013,
    Type: 4,
    Offsets: []
  },
  "10014": {
    Id: 10014,
    Type: 2,
    Offsets: []
  },
  "10015": {
    Id: 10015,
    Type: 0,
    Offsets: [[131.014, 89.549], [133.962, 97.657], [133.962, 97.657], [133.962, 97.657], [133.962, 97.657], [133.962, 97.657]]
  },
  "10016": {
    Id: 10016,
    Type: 6,
    Offsets: []
  }
}
