// Generated by file "Shop.xlsx"

export interface ShopItem {
  Id: number,
  Items: any
}

export const ShopData = {
  "1": {
    Id: 1,
    Items: [10004]
  },
  "2": {
    Id: 2,
    Items: [10003,10005,10008,10009,10014]
  },
  "3": {
    Id: 3,
    Items: [10002]
  },
  "4": {
    Id: 4,
    Items: []
  },
  "5": {
    Id: 5,
    Items: [10006,10011,10012,10016]
  },
  "6": {
    Id: 6,
    Items: [10007,10010]
  }
}
